name: Reusable workflow example

on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello@main
        with:
          greeting: ${{ inputs.username }}
