name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string

jobs:
  example_job:
    name: Pass greeting input to hello action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Documentated syntax fails to run as expected.
      #Workaround is to reference the full URI orgID/repoID/.github/actions/actionName@branch
      #- uses: ./.github/actions/hello
      - uses: azhub-testing/ausnet-actions/.github/actions/hello@main
        with:
          greeting: ${{ inputs.greeting }}
