name: Reusable workflow example

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string

jobs:
  example_job:
    name: Pass greeting input to hello action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/hello
        with:
          greeting: ${{ inputs.greeting }}
